apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: {{ .Values.buildConfig.name }}
spec:
  source:
    git:
      uri: {{ .Values.buildConfig.gitUri }}
      ref: {{ .Values.buildConfig.gitRef }}
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
